### ISSUE TITLE
`static`/`breathing` modes fail to light up bottom two lights

### ISSUE THREAD

**Issue by ThatOneCalculator** [crptmem/lianlinux#13]
Result of `sudo lianlinux light --mode static --red 28 --green 70 --blue 28`:

![image](https://github.com/crptmem/lianlinux/assets/44733677/88317be1-b44d-4742-8321-c05030b85136)

This does not occur with `rainbow`/`morph`

**Comment by crptmem** [comment]
Can you tell if it works with commit [22046b5](https://github.com/crptmem/lianlinux/commit/22046b58862c095f38f2b7e22435a8c0fdbc66f8)? I don't have a AIO with 3 fans, probably this issue is caused by wrong value in packet that sets LED count to change mode. I will investigate it further tomorrow.

**Comment by crptmem** [comment]
`rainbow` or `morph` is controlled by LianLi fan controller itself so all LEDs is lighted up.

**Comment by crptmem** [comment]
If it's not that difficult for you, you can run official Lian Li application in a VM with USB passthrough and try to set some modes using it with Wireguard capturing USB packets. This is not necessary, today I will try to figure out this problem. Thank you for your contributions!

**Comment by crptmem** [comment]
Try commit [85591d2](https://github.com/crptmem/lianlinux/commit/85591d2fba48e79d8d7a7ccff694c696e6114ef3), if it doesn't work please send me a picture of your AIO.

**Comment by ThatOneCalculator** [comment]
> Try commit [85591d2](https://github.com/crptmem/lianlinux/commit/85591d2fba48e79d8d7a7ccff694c696e6114ef3), if it doesn't work please send me a picture of your AIO.

Unfortunately that didn't fix it for me. My fans are not hooked into my AIO, just the case

**Comment by ThatOneCalculator** [comment]
> If it's not that difficult for you, you can run official Lian Li application in a VM with USB passthrough and try to set some modes using it with Wireshark capturing USB packets. This is not necessary, today I will try to figure out this problem. Thank you for your contributions!

I got a Windows 10 VM running with USB passthrough. I'm not very experienced with Wireshark, should I run it inside the VM or on Linux?

**Comment by ThatOneCalculator** [comment]
Got it working in the VM, what filter should I use?

![image](https://github.com/crptmem/lianlinux/assets/44733677/9a7b0c37-5f14-43fb-bbd1-7b046a496a08)

**Comment by crptmem** [comment]
Something like `static` and `breathing` because only they aren't working as expected. Thank you for your efforts.

**Comment by crptmem** [comment]
> > If it's not that difficult for you, you can run official Lian Li application in a VM with USB passthrough and try to set some modes using it with Wireshark capturing USB packets. This is not necessary, today I will try to figure out this problem. Thank you for your contributions!
> 
> I got a Windows 10 VM running with USB passthrough, and I'm able to change all the colors from there. I'm not very experienced with Wireshark, should I run it inside the VM or on Linux?

I was using Wireshark in Linux, but I think it can work in the VM. I don't know how to filter USB devices in Windows Wireshark, so I think you can just send the capture file here.

**Comment by ThatOneCalculator** [comment]
I'll be home in a couple hours so I'll send it then :)

**Comment by ThatOneCalculator** [comment]
Sorry about the late reply -- here's the USB packets for setting it to static `#AA00FF`

[gPrJ.zip](https://github.com/crptmem/lianlinux/files/14899875/gPrJ.zip)

**Comment by crptmem** [comment]
Hello. As I can see, `lianlinux` is sending a packet with wrong payload length (the colors in hex format). In provided screenshots you can see the right payload.
![2024-04-08_11-21](https://github.com/crptmem/lianlinux/assets/88046785/83e56ee6-685f-4b38-bc19-529f4f0e9fb7)\
I was rewriting `lianlinux` in Rust just for my comfort, and I tried to fix this issue in it. You can try it now by downloading binary from https://github.com/crptmem/lianlinux/releases/tag/rust-v0.1 or compiling it.
Run binary as superuser like this: `sudo lianlinux daemon` and you will be able to run `light` subcommand as a normal user.

**Comment by ThatOneCalculator** [comment]
I can test it tomorrow. Thank you for taking the time to fix this!

**Comment by ThatOneCalculator** [comment]
Can confirm it works as expected now!!! :tada: 

Thank you so much
