### ISSUE TITLE
Allow `lianlinux` commands without root if daemon is running

### ISSUE THREAD

**Issue by ThatOneCalculator** [crptmem/lianlinux#14]
If `lianlinux daemon` is running as root, the client should be able to send instructions to the daemon without also needing elevated access
![image](https://github.com/crptmem/lianlinux/assets/44733677/7fe8f6e2-7641-4c1b-8bc5-036c378432df)

**Comment by crptmem** [comment]
Done in [26bdf70](https://github.com/crptmem/lianlinux/commit/26bdf70c321e4b3fe3e6f36862b407b2211c22be), please switch to Rust version, thank you
