### ISSUE TITLE
Support the rest of the light modes

### ISSUE THREAD

**Issue by ThatOneCalculator** [crptmem/lianlinux#16]
I'd be happy to submit a USB dump for the rest of the lighting modes:

- Runaway
- Staggered
- Tide
- Mixing
- Stack
- Stack Multi Color
- Neon

since I imagine a lot of the modes are sent very similarly to how rainbow/color cycle/meteor are, please let me know if there's any specific way/order you want me to send it with

**Comment by crptmem** [comment]
I think you can just use all those modes while capturing USB packets in Wireshark and send me a capture file.

**Comment by crptmem** [comment]
Thank you, I'll check it out tomorrow.

**Comment by ThatOneCalculator** [comment]
tysm!

**Comment by crptmem** [comment]
Can you send me a video of `tide` effect? Cannot figure out how it works and how it should look.

**Comment by crptmem** [comment]
Sorry, I'm currently unable to add more features in `lianlinux` due to some personal issues and because I want to dedicate my time to some things or projects. I'll still maintain `lianlinux` and fix bugs tho!

**Comment by ThatOneCalculator** [comment]
No worries -- thank you for getting it this far!

**Comment by crptmem** [comment]
Please refer to issue #21.
