### ISSUE TITLE
Add explanation on how to use

### ISSUE THREAD

**Issue by logand99** [crptmem/lianlinux#19]
I am not familiar with rust at all. Can you explain or add steps on how to use this? Id love to make my LianLi stuff work on Linux

**Comment by crptmem** [comment]
If you already have Rust installed, follow [instructions on wiki](https://github.com/crptmem/lianlinux/wiki/Installation-and-usage). If you don't have Rust installed, [follow this instructions](https://www.rust-lang.org/tools/install) and then refer to lianlinux wiki.

**Comment by logand99** [comment]
My bad, I didnt see the side bar on the wiki.
 Wont run as expected though:

sudo /home/logan/.cargo/bin/lianlinux daemon
Found a LianLi-UNI FAN-SL-v1.8  controller
thread 'main' panicked at /home/logan/.cargo/registry/src/index.crates.io-6f17d22bba15001f/lianlinux-0.2.2/src/daemon/mod.rs:53:10:
called `Result::unwrap()` on an `Err` value: configuration file "/etc/lianlinux/config.toml" not found
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by crptmem** [comment]
You need to manually create a configuration file in `/etc/lianlinux/config.toml` and fill it in according to the wiki. I'll add a small fix to create the config file if it doesn't already exist. Sorry for the inconvenience.

**Comment by logand99** [comment]
Ah, I got it working now. Thank you! Between this and uni-sync I can control RGB and fans.

**Comment by crptmem** [comment]
By the way, fixed in version 0.2.3 ([742c9f9](https://github.com/crptmem/lianlinux/commit/742c9f9b1e71d39c1fd346a4433d2081e9cfbc43))
